### PR TITLE
Refactored WorkerMessage Factory Methods.

### PR DESCRIPTION
**Pull request by zuyu**
This PR refactored `WorkerMessage` factory methods and thus simplified code in `Foreman`.

### CODE REVIEW

**Comment by pateljm** [comment]
LTGM. Merging.

**Comment by hbdeshmukh** [comment]
@zuyu The three methods in WorkerMessage whose return type was changed from ``WorkerMessage`` to ``WorkerMessage*`` were actually [named constructors](https://isocpp.org/wiki/faq/ctors#named-ctor-idiom). If their return types are ``WorkerMessage*``, they won't be named constructors anymore. 

Also, I don't really understand why this change is needed. Can you expand on that?

**Comment by zuyu** [comment]
@hbdeshmukh I've changed them to `Factory Method`s, and thus avoid implicit `move` semantics you used and simplifies code.

**Comment by hbdeshmukh** [comment]
Was there any performance issue with the move semantics? Each message object is not heavy, just a couple of integers.

**Comment by zuyu** [comment]
But it is hard to use. That was why you had to add `Foreman::generateWorkerMessage` for the factory methods.

**Comment by hbdeshmukh** [comment]
Okay. The factory methods are not named constructors anymore, because of their return types.

**Comment by zuyu** [comment]
@hbdeshmukh Thanks for pointing it out, and I've fixed the comments in #88.

**Pull request merged**
