### PR TITLE
Quickstep sample operator

### PR DESCRIPTION
**Pull request by rogersjeffreyl**
This PR adds operator support for Sample.  The commits involving fixing of  review comments have been  squashed on to a  single commit.

### CODE REVIEW

**Comment by rogersjeffreyl** [comment]
@zuyu  I have squashed the commits onto a single one.  For some reason when I pushed the code the old pr got closed. Hence I have opened a new one.

**Comment by rogersjeffreyl** [comment]
@zuyu 

quickstep_queryoptimizer_tests_executiongenerator_insert test fails
The error message is :

WARNING: Failed to open file /home/travis/build/pivotalsoftware/quickstep/build/query_optimizer/tests/execution_generator/Insert/qsblk_0001_0000000000000000001.qsb with error: No such file or directory
F0317 06:27:35.910198 19047 StorageBlockBase.hpp:42] Check failed: 0 == getRefCount() (0 vs. 1) Nonzero ref_count_ when deleting block (1, 2)

This is an open issue currently being investigated by @cramja

**Comment by cramja** [comment]
I'd like to clarify, the first part of the error message (WARNING...) is what I am going to submit a PR for in the next few minutes, but the `refcount` bug is actually a more serious issue. In fact, I may have heard rumors that @pateljm  has placed a bounty on it.

**Comment by zuyu** [comment]
LGTM. There is a known ref counting bug.

**Pull request merged**
