### PR TITLE
Drop catalog initialization related files

### PR DESCRIPTION
**Pull request by pateljm**
Housecleaning: These files are no longer needed since PR #116.

### CODE REVIEW

**Comment by zuyu** [comment]
@pateljm There is a bug in the cli shell, but currently it cannot be found by the CI. And this is the reason why we need #73.

Please set [the default database init flag](https://github.com/pivotalsoftware/quickstep/blob/drop_catalog_init_files/cli/QuickstepCli.cpp#L144) to `true`, otherwise the cli crashes with the following log:

```
F0406 03:31:22.377707 1940639744 QuickstepCli.cpp:241] FATAL ERROR DURING STARTUP: UnableToReadCatalog: Unable to read catalog from file qsstor/catalog.pb.bin
*** Check failure stack trace: ***
    @        0x10ceb397a
    @        0x10ceb293b
    @        0x10ceb362a
    @        0x10ceba468
    @        0x10ceb3db5
    @        0x10ce585ea
Abort trap: 6
```

**Comment by pateljm** [comment]
@zuyu All the checks in Travis went through. 

Where is the bug? Are you suggesting that we should initialize a database by default. That is really odd default behavior.

**Comment by zuyu** [comment]
@pateljm Just run `./quickstep_cli_shell`, and you'll know what I was talking about.

**Comment by pateljm** [comment]
@zuyu I know what you are talking about! Read my comment carefully -- it is odd to initialize a database by default!

**Comment by zuyu** [comment]
As an alternative, check whether the catalog exists. If not, create one without crashing.

**Comment by pateljm** [comment]
What you are saying does not make sense. If the qsstor/catalog.pb.bin exists, we already check it.

**Comment by zuyu** [comment]
I am talking about the opposite. If the default catalog proto does not exist, we create one without crashing the system. It is ok that `-initialize_db` is `false` by default.

I just don't want to see that when a user first runs the system, it crashes due to no catalog.

**Comment by pateljm** [comment]
I think that is ok.

**Comment by zuyu** [comment]
As a part of this PR, we should remove this `TODO` comment:

https://github.com/pivotalsoftware/quickstep/blob/drop_catalog_init_files/cli/QuickstepCli.cpp#L197

**Comment by pateljm** [comment]
I added an message to provide hint to the user when there is no database and that they should initialize one. We may come back and revisit it later, but this is ok for now.

Good point about removing the TODO. Will do that now.

**Comment by zuyu** [comment]
I did not see any follow-up commit, until you told me in a comment later. It needs to fresh the page.

**Comment by pateljm** [comment]
No worries. Thanks for your input on this @zuyu. 

Cheers,
Jignesh

**Comment by zuyu** [comment]
FYI, the CI test does not cover changes to the CLI shell. We need to add a test to do so.

**Comment by pateljm** [comment]
Yup -- need to add end-to-end tests. Its on a TODO list and what lead me to add the MODULO operator.

**Pull request merged**
