### PR TITLE
Delay dropping table until all blocks get deleted.

### PR DESCRIPTION
**Pull request by zuyu**
This PR refactors `DropTableOperator` (updated by #43) to delay the table drop until all blocks get deleted. This avoids the dangling reference to the being-dropped `CatalogRelation` in the blocks.

This PR also provides a virtual method `RelationalOperator::updateCatalogOnCompletion` for other operators such as `CreateTableOperator` and `CreateIndexOperator`.

### CODE REVIEW

**Comment by pateljm** [comment]
This is neat @zuyu. Can we also mark the catalog as being in a state "pendingBlockDeletion" before the blocks are deleted. Thus, anyone looking at the catalog when the blocks are in this state have an idea that the catalog could be inconsistent (as there is a delay between the blocks deletions being initiated and the `updateCatalogOnCompletion` being called. 

Then, we can file an issue (closed in a different PR) that requires catalog calls to check for a potential inconsistent state before returning from it.

**Comment by zuyu** [comment]
@pateljm Added the suggested `Status` to indicate the inconsistent `CatalogDatabase` due to pending changes.

Please take another look! Thank you!

**Comment by zuyu** [comment]
@pateljm Please see my comment above. The database is `consistent` during the construction. Thanks!

**Comment by pateljm** [comment]
Thanks for the clarification @zuyu. LTGM. Merging.

**Pull request merged**
