### PR TITLE
Fixed the bug when worker affinities span across multiple NUMA nodes.

### PR DESCRIPTION
**Pull request by hbdeshmukh**
This PR fixes issue https://github.com/pivotalsoftware/quickstep/issues/37

Summary of changes:
- Created a new class to set the default configuration parameters.
- We count the number of NUMA nodes referenced by the worker
  affinities provided through the command line parameter.
- Reordering of constructor arguments in Foreman.
- Changed warning messages in InputParserUtil from GLOG to cout, so that
  the user knows about changes in number of workers or unused
  affinities.

### CODE REVIEW

**Comment by hbdeshmukh** [comment]
The failed build (one configuration using gcc) is because of the ``ref_count_`` issue.

**Comment by hbdeshmukh** [comment]
Fired the travis build again and now all of them succeed.

**Comment by pateljm** [comment]
Hi @hbdeshmukh Looks good - if you can resolve the conflicts, I can merge this. Thanks!

**Comment by hbdeshmukh** [comment]
Synced with the master.

**Comment by pateljm** [comment]
Merging now.

**Pull request merged**
