### PR TITLE
Add RE2 regular expression library as a third_party library.

### PR DESCRIPTION
**Pull request by jianqiao**
This PR is a preparation for implementing the string pattern matching feature (i.e. LIKE predicate and REGEXP predicate).

RE2 is a open-source regular expression library featured performance.The github repository for the RE2 project is https://github.com/google/re2.

`/third_party/re2` contains just a copy of what are in https://github.com/google/re2, except that `CMakeLists.txt` has been modified to fit our need.

### CODE REVIEW

**Comment by jianqiao** [comment]
@pateljm @zuyu Just find that `Assignee' can not be multiple persons. Please also help check whether the third_party library has been added in a appropriate way.

**Comment by zuyu** [comment]
I'd suggest to add `re2` as a `git submodule`.

https://github.com/google/re2

**Comment by zuyu** [comment]
Btw, what changes have you made to `re2`'s `CMakeLists`?

**Comment by jianqiao** [comment]
@zuyu It would be good if we can just add `re2` as a git submodule. But I'm not sure how to make the original `re2`'s `CMakeLists.txt` work. Can you help work on adding this submodule?

Btw, the changes to `CMakeLists.txt` are:
(1) Removed the benchmark & test build targets
(2) Added `-Wno-gnu -Wno-keyword-macro` flags for `clang` compiler, since re2 code contains _unnamed structs_ and _keyword redefined as macro_, which will raise compiler errors.

**Comment by zuyu** [comment]
We have the PR that adds `re2` as a submodule.

**Pull request closed without merging**
